simulator:
  record-count: 5
  datatype : cdr,nat
  # Allowed values:
  # cdr
  # nat
  # cdr,nat

  time-stamp: 2026-07-13
  timeperiod : 1000
  
  cdrhost: localhost
  cdrport: 5000
  
  nathost: localhost
  natport: 5001